<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "yag_item_view_count"
 *
 * Auto generated by Extension Builder 2014-09-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'YAG Item View Count',
	'description' => 'Adds a new attribute called \"view count\" to the item model of YAG for counting the views.',
	'category' => 'plugin',
	'author' => 'Patrick Baber',
	'author_email' => 'patrick@p-squared.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'yag' => '3.2.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);